/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Nisvarthjan Seva Foundation API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface ImpactStats {
  totalMembers: number;
  totalDonations: number;
  activeCampaigns: number;
  livesImpacted: number;
  villagesCovered: number;
  healthCampsOrganized: number;
  treesPlanted: number;
  scholarshipsGiven: number;
}

export interface Member {
  id: number;
  name: string;
  email: string;
  phone: string;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  state?: string | null;
  membershipType: string;
  membershipId: string;
  status: string;
  /** @nullable */
  certificateNumber?: string | null;
  joinedAt: string;
}

export type MemberInputMembershipType =
  (typeof MemberInputMembershipType)[keyof typeof MemberInputMembershipType];

export const MemberInputMembershipType = {
  general: "general",
  active: "active",
  lifetime: "lifetime",
} as const;

export interface MemberInput {
  /** @minLength 2 */
  name: string;
  email: string;
  phone: string;
  password: string;
  address?: string;
  city?: string;
  state?: string;
  membershipType: MemberInputMembershipType;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface AuthResponse {
  member: Member;
  token: string;
}

export interface MemberRegistrationResponse {
  member: Member;
  paymentMode: "manual" | "razorpay";
  payment?: {
    provider: "razorpay";
    keyId: string;
    orderId: string;
    amount: number;
    currency: "INR";
  };
}

export interface Campaign {
  id: number;
  title: string;
  /** @nullable */
  titleHindi?: string | null;
  description: string;
  /** @nullable */
  descriptionHindi?: string | null;
  goalAmount: number;
  raisedAmount: number;
  category: string;
  /** @nullable */
  imageUrl?: string | null;
  isActive: boolean;
  createdAt: string;
  donorCount: number;
}

export interface Donation {
  id: number;
  amount: number;
  donorName: string;
  donorEmail: string;
  /** @nullable */
  donorPhone?: string | null;
  /** @nullable */
  campaignId?: number | null;
  purpose: string;
  receiptNumber: string;
  status?: string;
  paymentStatus?: string;
  payment?: {
    provider: "razorpay";
    keyId: string;
    orderId: string;
    amount: number;
    currency: "INR";
  };
  createdAt: string;
}

export interface DonationInput {
  /** @minimum 1 */
  amount: number;
  donorName: string;
  donorEmail: string;
  donorPhone?: string;
  campaignId?: number;
  purpose: string;
}

export interface NewsArticle {
  id: number;
  title: string;
  /** @nullable */
  titleHindi?: string | null;
  content: string;
  /** @nullable */
  contentHindi?: string | null;
  /** @nullable */
  excerpt?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  category: string;
  publishedAt: string;
  /** @nullable */
  author?: string | null;
}

export interface CertificateVerification {
  isValid: boolean;
  documentType?: string;
  verificationId?: string;
  certificateNumber: string;
  /** @nullable */
  memberName?: string | null;
  /** @nullable */
  membershipId?: string | null;
  /** @nullable */
  membershipType?: string | null;
  /** @nullable */
  issuedAt?: string | null;
  status: string;
}

export interface ContactInput {
  name: string;
  email: string;
  phone?: string;
  message: string;
}

export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  /** @nullable */
  phone?: string | null;
  message: string;
  createdAt: string;
}

export interface Testimonial {
  id: number;
  name: string;
  /** @nullable */
  designation?: string | null;
  content: string;
  /** @nullable */
  contentHindi?: string | null;
  /** @nullable */
  imageUrl?: string | null;
}

export interface GalleryImage {
  id: number;
  imageUrl: string;
  /** @nullable */
  caption?: string | null;
  /** @nullable */
  captionHindi?: string | null;
  /** @nullable */
  detailsEn?: string | null;
  /** @nullable */
  detailsHi?: string | null;
  category: string;
  createdAt: string;
}

export type VerifyCertificateParams = {
  certificateNumber?: string;
  verificationId?: string;
  documentType?: string;
  contact?: string;
};
