/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Nisvarthjan Seva Foundation API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthResponse,
  Campaign,
  CertificateVerification,
  ContactInput,
  ContactMessage,
  Donation,
  DonationInput,
  ErrorResponse,
  GalleryImage,
  HealthStatus,
  ImpactStats,
  LoginInput,
  Member,
  MemberInput,
  MemberRegistrationResponse,
  NewsArticle,
  Testimonial,
  VerifyCertificateParams,
} from "./api.schemas";
export * from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get impact statistics
 */
export const getGetStatsUrl = () => {
  return `/api/stats`;
};

export const getStats = async (options?: RequestInit): Promise<ImpactStats> => {
  return customFetch<ImpactStats>(getGetStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get impact statistics
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new member
 */
export const getRegisterMemberUrl = () => {
  return `/api/members`;
};

export const registerMember = async (
  memberInput: MemberInput,
  options?: RequestInit,
): Promise<MemberRegistrationResponse> => {
  return customFetch<MemberRegistrationResponse>(getRegisterMemberUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(memberInput),
  });
};

export const getRegisterMemberMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerMember>>,
    TError,
    { data: BodyType<MemberInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerMember>>,
  TError,
  { data: BodyType<MemberInput> },
  TContext
> => {
  const mutationKey = ["registerMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerMember>>,
    { data: BodyType<MemberInput> }
  > = (props) => {
    const { data } = props ?? {};

    return registerMember(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerMember>>
>;
export type RegisterMemberMutationBody = BodyType<MemberInput>;
export type RegisterMemberMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Register a new member
 */
export const useRegisterMember = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerMember>>,
    TError,
    { data: BodyType<MemberInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerMember>>,
  TError,
  { data: BodyType<MemberInput> },
  TContext
> => {
  return useMutation(getRegisterMemberMutationOptions(options));
};

/**
 * @summary Member login
 */
export const getLoginMemberUrl = () => {
  return `/api/auth/login`;
};

export const loginMember = async (
  loginInput: LoginInput,
  options?: RequestInit,
): Promise<AuthResponse> => {
  return customFetch<AuthResponse>(getLoginMemberUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginInput),
  });
};

export const getLoginMemberMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginMember>>,
    TError,
    { data: BodyType<LoginInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginMember>>,
  TError,
  { data: BodyType<LoginInput> },
  TContext
> => {
  const mutationKey = ["loginMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginMember>>,
    { data: BodyType<LoginInput> }
  > = (props) => {
    const { data } = props ?? {};

    return loginMember(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginMember>>
>;
export type LoginMemberMutationBody = BodyType<LoginInput>;
export type LoginMemberMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Member login
 */
export const useLoginMember = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginMember>>,
    TError,
    { data: BodyType<LoginInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginMember>>,
  TError,
  { data: BodyType<LoginInput> },
  TContext
> => {
  return useMutation(getLoginMemberMutationOptions(options));
};

/**
 * @summary Member logout
 */
export const getLogoutMemberUrl = () => {
  return `/api/auth/logout`;
};

export const logoutMember = async (options?: RequestInit): Promise<void> => {
  return customFetch<void>(getLogoutMemberUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutMemberMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutMember>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutMember>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutMember>>,
    void
  > = () => {
    return logoutMember(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutMember>>
>;

export type LogoutMemberMutationError = ErrorType<unknown>;

/**
 * @summary Member logout
 */
export const useLogoutMember = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutMember>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutMember>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutMemberMutationOptions(options));
};

/**
 * @summary Get current logged in member
 */
export const getGetMeUrl = () => {
  return `/api/auth/me`;
};

export const getMe = async (options?: RequestInit): Promise<Member> => {
  return customFetch<Member>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetMeQueryKey = () => {
  return [`/api/auth/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = ErrorType<void>;

/**
 * @summary Get current logged in member
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all campaigns
 */
export const getListCampaignsUrl = () => {
  return `/api/campaigns`;
};

export const listCampaigns = async (
  options?: RequestInit,
): Promise<Campaign[]> => {
  return customFetch<Campaign[]>(getListCampaignsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListCampaignsQueryKey = () => {
  return [`/api/campaigns`] as const;
};

export const getListCampaignsQueryOptions = <
  TData = Awaited<ReturnType<typeof listCampaigns>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCampaigns>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCampaignsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCampaigns>>> = ({
    signal,
  }) => listCampaigns({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCampaigns>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCampaignsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCampaigns>>
>;
export type ListCampaignsQueryError = ErrorType<unknown>;

/**
 * @summary List all campaigns
 */

export function useListCampaigns<
  TData = Awaited<ReturnType<typeof listCampaigns>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listCampaigns>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCampaignsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get campaign by ID
 */
export const getGetCampaignUrl = (id: number) => {
  return `/api/campaigns/${id}`;
};

export const getCampaign = async (
  id: number,
  options?: RequestInit,
): Promise<Campaign> => {
  return customFetch<Campaign>(getGetCampaignUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetCampaignQueryKey = (id: number) => {
  return [`/api/campaigns/${id}`] as const;
};

export const getGetCampaignQueryOptions = <
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCampaign>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCampaignQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCampaign>>> = ({
    signal,
  }) => getCampaign(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCampaign>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCampaignQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCampaign>>
>;
export type GetCampaignQueryError = ErrorType<void>;

/**
 * @summary Get campaign by ID
 */

export function useGetCampaign<
  TData = Awaited<ReturnType<typeof getCampaign>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCampaign>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCampaignQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Submit a donation
 */
export const getCreateDonationUrl = () => {
  return `/api/donations`;
};

export const createDonation = async (
  donationInput: DonationInput,
  options?: RequestInit,
): Promise<Donation> => {
  return customFetch<Donation>(getCreateDonationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(donationInput),
  });
};

export const getCreateDonationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDonation>>,
    TError,
    { data: BodyType<DonationInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDonation>>,
  TError,
  { data: BodyType<DonationInput> },
  TContext
> => {
  const mutationKey = ["createDonation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDonation>>,
    { data: BodyType<DonationInput> }
  > = (props) => {
    const { data } = props ?? {};

    return createDonation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDonationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDonation>>
>;
export type CreateDonationMutationBody = BodyType<DonationInput>;
export type CreateDonationMutationError = ErrorType<unknown>;

/**
 * @summary Submit a donation
 */
export const useCreateDonation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDonation>>,
    TError,
    { data: BodyType<DonationInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createDonation>>,
  TError,
  { data: BodyType<DonationInput> },
  TContext
> => {
  return useMutation(getCreateDonationMutationOptions(options));
};

/**
 * @summary List news articles
 */
export const getListNewsUrl = () => {
  return `/api/news`;
};

export const listNews = async (
  options?: RequestInit,
): Promise<NewsArticle[]> => {
  return customFetch<NewsArticle[]>(getListNewsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListNewsQueryKey = () => {
  return [`/api/news`] as const;
};

export const getListNewsQueryOptions = <
  TData = Awaited<ReturnType<typeof listNews>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listNews>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListNewsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listNews>>> = ({
    signal,
  }) => listNews({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listNews>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListNewsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listNews>>
>;
export type ListNewsQueryError = ErrorType<unknown>;

/**
 * @summary List news articles
 */

export function useListNews<
  TData = Awaited<ReturnType<typeof listNews>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof listNews>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListNewsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get news article by ID
 */
export const getGetNewsArticleUrl = (id: number) => {
  return `/api/news/${id}`;
};

export const getNewsArticle = async (
  id: number,
  options?: RequestInit,
): Promise<NewsArticle> => {
  return customFetch<NewsArticle>(getGetNewsArticleUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetNewsArticleQueryKey = (id: number) => {
  return [`/api/news/${id}`] as const;
};

export const getGetNewsArticleQueryOptions = <
  TData = Awaited<ReturnType<typeof getNewsArticle>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getNewsArticle>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNewsArticleQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNewsArticle>>> = ({
    signal,
  }) => getNewsArticle(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getNewsArticle>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetNewsArticleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getNewsArticle>>
>;
export type GetNewsArticleQueryError = ErrorType<void>;

/**
 * @summary Get news article by ID
 */

export function useGetNewsArticle<
  TData = Awaited<ReturnType<typeof getNewsArticle>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getNewsArticle>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetNewsArticleQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Verify a certificate
 */
export const getVerifyCertificateUrl = (params: VerifyCertificateParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/certificates/verify?${stringifiedParams}`
    : `/api/certificates/verify`;
};

export const verifyCertificate = async (
  params: VerifyCertificateParams,
  options?: RequestInit,
): Promise<CertificateVerification> => {
  return customFetch<CertificateVerification>(getVerifyCertificateUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getVerifyCertificateQueryKey = (
  params?: VerifyCertificateParams,
) => {
  return [`/api/certificates/verify`, ...(params ? [params] : [])] as const;
};

export const getVerifyCertificateQueryOptions = <
  TData = Awaited<ReturnType<typeof verifyCertificate>>,
  TError = ErrorType<void>,
>(
  params: VerifyCertificateParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof verifyCertificate>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getVerifyCertificateQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof verifyCertificate>>
  > = ({ signal }) => verifyCertificate(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof verifyCertificate>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type VerifyCertificateQueryResult = NonNullable<
  Awaited<ReturnType<typeof verifyCertificate>>
>;
export type VerifyCertificateQueryError = ErrorType<void>;

/**
 * @summary Verify a certificate
 */

export function useVerifyCertificate<
  TData = Awaited<ReturnType<typeof verifyCertificate>>,
  TError = ErrorType<void>,
>(
  params: VerifyCertificateParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof verifyCertificate>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getVerifyCertificateQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Submit contact form
 */
export const getSubmitContactUrl = () => {
  return `/api/contact`;
};

export const submitContact = async (
  contactInput: ContactInput,
  options?: RequestInit,
): Promise<ContactMessage> => {
  return customFetch<ContactMessage>(getSubmitContactUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(contactInput),
  });
};

export const getSubmitContactMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitContact>>,
    TError,
    { data: BodyType<ContactInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitContact>>,
  TError,
  { data: BodyType<ContactInput> },
  TContext
> => {
  const mutationKey = ["submitContact"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitContact>>,
    { data: BodyType<ContactInput> }
  > = (props) => {
    const { data } = props ?? {};

    return submitContact(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SubmitContactMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitContact>>
>;
export type SubmitContactMutationBody = BodyType<ContactInput>;
export type SubmitContactMutationError = ErrorType<unknown>;

/**
 * @summary Submit contact form
 */
export const useSubmitContact = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitContact>>,
    TError,
    { data: BodyType<ContactInput> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitContact>>,
  TError,
  { data: BodyType<ContactInput> },
  TContext
> => {
  return useMutation(getSubmitContactMutationOptions(options));
};

/**
 * @summary List testimonials
 */
export const getListTestimonialsUrl = () => {
  return `/api/testimonials`;
};

export const listTestimonials = async (
  options?: RequestInit,
): Promise<Testimonial[]> => {
  return customFetch<Testimonial[]>(getListTestimonialsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListTestimonialsQueryKey = () => {
  return [`/api/testimonials`] as const;
};

export const getListTestimonialsQueryOptions = <
  TData = Awaited<ReturnType<typeof listTestimonials>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listTestimonials>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTestimonialsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listTestimonials>>
  > = ({ signal }) => listTestimonials({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTestimonials>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTestimonialsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTestimonials>>
>;
export type ListTestimonialsQueryError = ErrorType<unknown>;

/**
 * @summary List testimonials
 */

export function useListTestimonials<
  TData = Awaited<ReturnType<typeof listTestimonials>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listTestimonials>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTestimonialsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List gallery images
 */
export const getListGalleryUrl = () => {
  return `/api/gallery`;
};

export const listGallery = async (
  options?: RequestInit,
): Promise<GalleryImage[]> => {
  return customFetch<GalleryImage[]>(getListGalleryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListGalleryQueryKey = () => {
  return [`/api/gallery`] as const;
};

export const getListGalleryQueryOptions = <
  TData = Awaited<ReturnType<typeof listGallery>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGallery>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListGalleryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listGallery>>> = ({
    signal,
  }) => listGallery({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGallery>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListGalleryQueryResult = NonNullable<
  Awaited<ReturnType<typeof listGallery>>
>;
export type ListGalleryQueryError = ErrorType<unknown>;

/**
 * @summary List gallery images
 */

export function useListGallery<
  TData = Awaited<ReturnType<typeof listGallery>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listGallery>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListGalleryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
